package com.inboxintelligence.persistence.model;

public enum ProcessedStatus {
    RECEIVED,
    CONTENT_SAVED,
    ATTACHMENT_SAVED,
    PUBLISHED_FOR_SANITIZATION,
    CONSUMED_FOR_SANITIZATION,
    SANITIZATION_STARTED,
    SANITIZATION_COMPLETED,
    PUBLISHED_FOR_EMBEDDING,
    CONSUMED_FOR_EMBEDDING,
    EMBEDDING_GENERATED,
    EMBEDDING_SAVED,
    PROCESSING_FAILED
}
