package com.inboxintelligence.persistence.model;

public enum ProcessedStatus {


    EMAIL_RECEIVED,
    CONTENT_SAVED,
    ATTACHMENT_SAVED,
    INGESTION_FAILED,

    PUBLISHED_FOR_SANITIZATION,
    SANITIZATION_STARTED,
    SANITIZATION_COMPLETED,
    SANITIZATION_FAILED,

    PUBLISHED_FOR_EMBEDDING,
    EMBEDDING_STARTED,
    EMBEDDING_GENERATED,
    EMBEDDING_FAILED,

    PUBLISHED_FOR_CLUSTER_ASSIGNMENT,
    CLUSTER_ASSIGNMENT_STARTED,
    CLUSTER_ASSIGNMENT_COMPLETED,
    CLUSTER_ASSIGNMENT_FAILED,

    UNKNOWN_FAILURE;

}
